# Generated by Django 2.2.10 on 2021-06-20 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionreply',
            options={'verbose_name': 'Ответы', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='questions.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Варианты ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
    ]
