# Generated by Django 2.2.10 on 2021-06-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210620_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='uid',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
